### ISSUE TITLE
Release 1 - [MASTER ISSUE TRACKER]

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#34]
**This is a tracker of the outstanding issues that need to be addressed for Release 1.**

---

**9/4 - 9/10**
- [x] Pane hide/show, #31 
- [x] Remove ModelView, #37
- [x] Remove output TS, #41
- [x] File browser / toolbox views, #36 

---

**9/11 - 9/17**
- [x] Right click detail view, #25
- [x] File browser buttons, #39
- [x] Model toolbox layout, #40
- [x] Link Details back button not working, #44
- [x] AddLink wizard title, #45

---

_Mario_
- [x] View details not working, #42  
  
  > - Put "Model Details" in to application View menu
- [x] Fix menus, #38 
  
  > - Fix "Save Simulation".  Ghost out "Load Simulation"
- [ ] Populate link details ,#43
  
  > - Use one class
- [x] Link Edit Buttons, #46
  
  > - rename "Clear All" to "Remove".  Remove "Edit" button
- [x] Launch application from command line, #47
- Clean output and reactivate the output panel

_Tony_
- [ ] Temporal mapping, #32 
- [ ] Spatial mapping, #33 
- [x] Get SWMM running, #48

_Push to Release 1.1_
- [ ] Nav Toolbar zoom/pan Broken, #26 
- [x] Application close error, #15 
- [ ] Simulation data save is slow, #30 
- [ ] Data export, #35 
- [ ] Model Tools Need Setup Dialog Window, #53

---

**10/1/14**
- [ ] Refactor Code!!!!!
