### ISSUE TITLE
Release 1.0 Checklist

### ISSUE THREAD

**Issue by Castronova** [Castronova/EMIT#465]
A checklist of required items for EMIT release 1.0

**Installers**
- [ ] OSX
- [ ] Linux
- [ ] Windows 10

**Engine**
- [ ] Feed-forward simulation
- [ ] Time-step simulation
- [ ] Unit Conversions
- [ ] Temporal Mapping
- [ ] Spatial Mapping

**Examples**
- [ ] UEB - TOPMODEL 
- [ ] UEB - TOPKAPI

**GUI**

**Documentation**
- [ ] Model Execution (GUI)
- [ ] Model Execution (terminal)
- [ ] Creating new model components
- [ ] Adding new data sources

**Comment by farrieta9** [comment]
Perhaps also if I may add, we should fix running simulations.
